### ISSUE TITLE
Project implicitly depends on torch nightly

### ISSUE THREAD

**Issue by ELanning** [pytorch-labs/ao#29]
```
Traceback (most recent call last):
  File "C:\code\foo\scripts\quantize.py", line 4, in <module>
    from torchao.quantization.smoothquant import (
  File "C:\code\py-envs\foo\lib\site-packages\torchao\quantization\__init__.py", line 7, in <module>
    from .smoothquant import *  # noqa: F403
  File "C:\code\py-envs\foo\lib\site-packages\torchao\quantization\smoothquant.py", line 17, in <module>
    import torchao.quantization.quant_api as quant_api
  File "C:\code\py-envs\foo\lib\site-packages\torchao\quantization\quant_api.py", line 18, in <module>
    from .subclass import (
  File "C:\code\py-envs\foo\lib\site-packages\torchao\quantization\subclass.py", line 13, in <module>
    from torch.utils._python_dispatch import return_and_correct_aliasing
ImportError: cannot import name 'return_and_correct_aliasing' from 'torch.utils._python_dispatch' (C:\code\py-envs\foo\lib\site-packages\torch\utils\_python_dispatch.py)
```

This project seems to rely on torch nightly, which exports `return_and_correct_aliasing`. It might be worthwhile to document this. I suppose one could argue it's obvious enough from this being an experimental repo, but it was surprising to me.

Nice work team, I'm looking forward to using this package.

**Comment by HDCharles** [comment]
What version of pytorch were you using out of curiosity?

i'll add some info to the readme, there are a variety of torch version issues for the subclass api's the module swap api's should work fine

**Comment by ELanning** [comment]
I was using the latest torch stable 2.1.2 on cuda 11.8. (`return_and_correct_aliasing` does not yet exist there)

**Comment by HDCharles** [comment]
Yeah the module swap APIs should work in that case

**Comment by TimPietrusky** [comment]
> Yeah the module swap APIs should work in that case

You mean when using torch 2.1.2?
